config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions",
                                    confirmations: "users/confirmations",
                                    registrations: "users/registrations"}

  namespace :users do
    get   :invite
    post  :create_invite
    put   :update
    patch :save_profile
    post  :save_transaction
    get   :list
  end

  get 'users/show/:id' => 'users#show', as: 'users'
  get 'users/:id/edit' => 'users#edit', as: 'edit'
  get 'users/:id/take' => 'users#take', as: 'take'
  get 'users/:id/give' => 'users#give', as: 'give'

  root :to => "users#index"

end

app/models/shared_bank.rb
class SharedBank < ActiveRecord::Base
  validates :current, presence: true

  def self.update_balance(params)

    if self.take? params
      return self.take params[:balance].to_i
    else
      return self.give params[:balance].to_i
    end
  end

  private

  def self.take(balance)
    current = SharedBank.last.current

    if (updated_balance = current - balance) >= 0
      SharedBank.last
          .update_attribute(:current, updated_balance)

      return true
    else
      return false
    end
  end

  def self.give(balance)
    current = SharedBank.last.current

    SharedBank.last
        .update_attribute(:current, (current + balance))

    return true
  end

  def self.take?(params)
    params[:take] == "true"
  end

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  validates :balance, presence: true
  validate :balance do |record|
    balance_validation record
  end


  private

  def balance_validation(record)

    if record.balance.to_i > SharedBank.last.current.to_i
      record.errors[:base] << "There are not enough money in Shared Bank, plese choose another balance"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  # Paperclip avatar validations
  has_attached_file :avatar, :styles => { :medium => "240x240>", :thumb => "80x80>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Associations
  has_many :transactions

  # Taken balance
  def self.balance_take(id)
    return self.totally(id).to_a.last[1].to_i
  end

  # Given balance
  def self.balance_give(id)
    return self.totally(id).first[1].to_i
  end

  private

  def self.totally(id)
    totally = Transaction.group(:user_id, :take)
                   .having(user_id: id)
                   .sum(:balance)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :check_admin

  private

  def check_admin

    if !current_user.nil? && !current_user.admin?

      redirect_to new_user_session_url, :flash => { :access_error => "Only Admin can give you access" }
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  skip_before_action :check_admin

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  skip_before_action :check_admin

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
     super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user!, only: :index
  before_action :show_user, only: [:show, :edit]
  skip_before_action :check_admin, only: [:list, :invite, :create_invite]

  PASSWORD_LENGTH = 10

  ##
  # Show current bank balance
  # #
  def index
    if @bank_balance = SharedBank.last
      @bank_balance = @bank_balance.current.to_i
    else
      #Empty bank balance
      @bank_balance = 0
    end
  end

  ##
  # Show users list
  # #
  def list
    @users = User.all
  end

  ##
  # Admin part
  # Create invite to user
  # GET @email
  # #

  def invite
    @user = User.new
  end

  def create_invite

    email = name = params[:user][:email]
    password = Devise.friendly_token.first(PASSWORD_LENGTH)

    if User.find_by(:email => email).nil?
      @user = User.create!({ :name => name,
                             :email => email,
                             :password => password,
                             :password_confirmation => password })
    else
      #Already registered
    end

    redirect_to root_path
  end

  ##
  # Only for current user
  # Show user profile
  # Show user transaction
  # Get @current_user
  # #

  def show
    @user = User.find(params[:id])
    @transactions =  User.find(current_user.id)
                         .transactions
                         .order(created_at: :desc)
                         .paginate(:page => params[:page], :per_page => 5)

    @given = User.balance_give params[:id]
    @taken = User.balance_take params[:id]
  end

  def edit
    @user = User.find(params[:id])
  end

  def save_profile

    user = User.find(current_user.id)

    user.update_attributes(user_params)

    redirect_to root_path
  end

  ##
  # Only for current user
  # Create positive transaction
  # Create negative transaction
  # Get @current_user
  # #

  def take
    @transaction = Transaction.new
  end

  def give
    @transaction = Transaction.new
  end

  def save_transaction

    if SharedBank.update_balance(params[:transaction])
      @transaction = Transaction.create(transaction_params)
    else
      flash[:access_error] = "There are not enough money in Shared Bank, plese choose another balance"
    end

    redirect_to users_path(current_user.id)
  end


  private

  # Check profile page access
  def show_user

    if !current_user?
      flash[:access_error] = "You cant get access to this page"
      redirect_to root_path
    end
  end

  def current_user?

    return false if current_user.blank?
    current_user.id == params[:id].to_i
  end

  # User params validation
  def user_params
    params.require(:user).permit(:name, :password, :avatar)
  end

  # Transaction params validation
  def transaction_params
    params.require(:transaction).permit(:balance, :take, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="panel-footer">
  <% if current_user.nil? %>
      <%= link_to 'Sign in', new_user_session_path %>
  <% else %>
      <%= link_to 'My Profile', users_path(current_user.id) %>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
  <% end %>

  <% if current_user && current_user.admin? %>
      <%= link_to 'Invite user', users_invite_path %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <% link_to 'Shared Bank', root_path, class: 'navbar-brand' %>
  </div>
  <div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to 'Shared Bank', root_path, class: 'navbar-brand' %>
      </li>
      <% if current_user.nil? %>
          <li>
            <%= link_to 'Sign in',  new_user_session_path %>
          </li>
      <% else %>
          <li>
            <%= link_to 'Give money', give_path(current_user.id), class: 'give' %>
          </li>
          <li>
            <%= link_to 'Take money', take_path(current_user.id), class: 'take' %>
          </li>
          <li>
            <%= link_to 'My Profile', users_path(current_user.id) %>
          </li>
          <li>
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
          </li>
      <% end %>
      <% if current_user && current_user.admin? %>
          <li>
            <%= link_to 'Invite user', users_invite_path %>
          </li>
          <li>
            <%= link_to 'Users list', users_list_path %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container center hero-unit">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/users/_form.html.erb
<%= f.hidden_field :user_id, value: current_user.id %>

<div class="field">
  <%= f.label :balance %>
  <%= f.number_field :balance, value: 0, min: 0, step: 1 %>
  <%= f.submit %>
</div>

app/views/users/_transactions.html.erb
<% flash.each do |name, msg| -%>
    <%= content_tag :h3, msg, class: :get %>
<% end %>

<table class="table" style="margin-top: 10%;">

  <thead>
    <th>N</th>
    <th>Transaction balance</th>
    <th>Date of transaction</th>
  </thead>

  <tbody>
  <% @transactions.each_with_index do |transaction, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td class="<% if transaction[:take] %>take<% else %>give<% end %>">
          <%= transaction[:balance] %>
        </td>
        <td><%= transaction[:created_at] %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @transactions %>

<h3 class="give">Totally given: <%= @given %></h3>
<h3 class="take">Totally taken: <%= @taken %></h3>

<h1 class="<% if (balance = @given - @taken) >= 0 %>give<% else %>take<% end %>">
  Your balance: <%= balance %>
</h1>

<% if balance < 0 %>
    <%= link_to 'Return money', give_path(current_user.id), class: 'btn btn-default' %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<div class="center hero-unit">

  <%= form_for(@user, url: {action: "save_profile"}) do |f| %>
      <table class="table">
        <tbody>
        <th>New name</th>
        <th>New password</th>
        <th>Image</th>
        <tr>
          <td><%= f.text_field :name, :value => current_user.name %></td>
          <td><%= f.password_field :password, :value => current_user.password %></td>
          <td><%= f.file_field :avatar, class: 'btn btn-default' %></td>
        </tr>
        </tbody>
      </table>
      <%= f.submit 'Save', class: 'btn btn-default' %>
  <% end %>
</div>

app/views/users/give.html.erb
<%= form_for(@transaction, url: {action: "save_transaction"}) do |f| %>

    <%= f.hidden_field :take, value: false %>

    <%= render 'users/form', f: f %>
<% end %>

app/views/users/index.html.erb
<h1>Sloboda Shared Bank</h1>

<h3 class="give">Current bank balance</h3>

<h1><%= @bank_balance %></h1>

<%= image_tag 'bank.jpeg' %>

<h3 class="desc">
  Be care about bank
</h3>

app/views/users/invite.html.erb
<h1>Invite</h1>

<div class="center hero-unit">
  <%= form_for(@user, url: {action: "create_invite"}) do |f| %>
      <p> User Email: <%= f.text_field :email %> </p>
      <%= f.submit :Invite %>
  <% end %>
</div>

app/views/users/list.html.erb
<table class="table" style="margin-top: 10%;">

  <thead>
    <th>N</th>
    <th>Avatar</th>
    <th>Name</th>
    <th>Email</th>
    <th>Confirmed</th>
    <th>Date</th>
  </thead>

  <tbody>
  <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td>
          <% if user.avatar? %>
              <%= image_tag(user.avatar.url(:thumb) , class: 'avatar thumb') %>
          <% else %>
              <%= image_tag('default_avatar.png', class: 'avatar thumb') %>
          <% end %>
        </td>
        <td><%= user[:name] %></td>
        <td><%= user[:email] %></td>
        <td class="<% if token = user[:confirmation_token].length > 0 %>give<% else %>take<% end %>">
          <% if token %>
            true
          <% else %>
           false
          <% end %>
        </td>
        <td><%= user[:created_at] %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>My profile</h1>

<% if @user.errors.any? %>
    <% @user.errors.each do |attribute, message| %>
        <div class="error">
          <%= message %>
        </div>
     <% end %>
<% end %>

<% if @user.avatar? %>
    <%= image_tag(@user.avatar.url(:medium) , class: 'avatar') %>
<% else %>
    <%= image_tag('default_avatar.png', class: 'avatar') %>
<% end %>

<p class="desc">Profile image</p>

<table class="table" style="margin-top: 10%;">
  <tbody>
  <th>Name</th>
  <th>Email</th>
  <th>Signed in times</th>
  <th>Date of registration</th>
  <tr>
    <td><%= @user[:name] %></td>
    <td><%= @user[:email] %></td>
    <td><%= @user[:sign_in_count] %></td>
    <td><%= @user[:created_at] %></td>
  </tr>
  </tbody>
</table>

<%= link_to 'Edit Profile', edit_path(current_user.id), class: 'btn btn-default' %>

<h1>Transactions</h1>

<%= render 'users/transactions' %>

app/views/users/take.html.erb
<%= form_for(@transaction, url: {action: "save_transaction"}) do |f| %>

    <%= f.hidden_field :take, value: true %>

    <%= render 'users/form', f: f %>
<% end %>